# include <iostream>
using namespace std;

int main() {
        cout << "bbews";
        cout << "twfwt";
        cout << "xfuhw";
        cout << "apnjj";
        cout << "nbmff";
        cout << "eqjji";
        cout << "gkjnp";
        cout << "ygmjm";
        cout << "eftwp";
        cout << "fwhfb";
        cout << "ahota";
        cout << "evtpr";
        cout << "lmfbl";
        cout << "nhqqy";
        cout << "dktpf";
        cout << "nyrhc";
        cout << "iimon";
        cout << "vsqpf";
        cout << "flkob";
        cout << "ejhmd";
        cout << "dwjxy";
        cout << "nesyk";
        cout << "iclix";
        cout << "aetyx";
        cout << "ahufv";
        cout << "aydhe";
        cout << "rnxct";
        cout << "mdujn";
        cout << "imhgu";
        cout << "wogsu";
        cout << "magob";
        cout << "qhsii";
        cout << "gnkqs";
        cout << "pwgwq";
        cout << "gkvhe";
        cout << "wakxt";
        cout << "pipjf";
        cout << "uihos";
        cout << "oqamp";
return 0;
}
