name: "Update contributions"

on:
  schedule:
  - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
         python-version: 3.8

      - name: Clone importer script repo
        uses: actions/checkout@v2
        with:
          repository: https://github.com/miromannino/Contributions-Importer-For-Github.git

      - name: Setup GitLab SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: gitlab.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY_GITLAB }}
          private-key-name: github_actions

      - name: Clone first GitLab repository
        run: git clone ${{ secrets.FIRST_GITLAB_REPO }} /tmp/first
      
      - name: Run importer script
        run: ls
