name: "Update contributions"

on:
  schedule:
  - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Setup git creditationals
        run: git config --global user.email "i.prostoi.chelovek@yandex.ru" \
             git config --global user.name "prostoichelovek"

      - name: Setup python
        uses: actions/setup-python@v2
        with:
         python-version: 3.8

      - name: Clone importer script repo
        run: git clone https://github.com/miromannino/Contributions-Importer-For-Github.git

      - name: Install importer script dependencies
        run: python3 -m pip install gitpython pathlib

      - name: Setup GitLab SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: gitlab.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY_GITLAB }}
          private-key-name: github_actions

      - name: Clone the first GitLab repository
        run: git clone -b dev ${{ secrets.FIRST_GITLAB_REPO }} /tmp/first

      - name: Clone the second GitLab repository
        run: git clone -b dev ${{ secrets.SECOND_GITLAB_REPO }} /tmp/second

      - name: Run importer script on the first repo
        run: python3 run.py /tmp/first

      - name: Run importer script on the second repo
        run: python3 run.py /tmp/second

      - name: Push created commits
        run: git push

      - name: Remove clonned repos
        run: rm -rf /tmp/first && rm -rf /tmp/second
